<a href="https://colab.research.google.com/github/Huii0529/Data-Management/blob/main/Week12_DataWrangling_20260606.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Week 12: Data Wrangling**

Data wrangling is the process of preparing raw data into a clean, structured, and analysis-ready format.
- In real-world data analysis, datasets often contain missing values, duplicate records, inconsistent formats, outliers, and information stored across multiple tables.

In this notebook, we will learn how to clean, transform, combine, and reshape data using pandas and NumPy. These skills are important before performing statistical analysis, data visualization, or machine learning.

## **Learning Outcomes**

By the end of this notebook, students should be able to:

1. Identify and handle missing values in a dataset.
2. Remove duplicate records from a DataFrame.
3. Transform values using mapping, replacement, renaming, and binning.
4. Detect and manage extreme values or outliers.
5. Perform permutation and random sampling.
6. Clean and manipulate string data.
7. Work with categorical variables and dummy variables.
8. Combine datasets using merging and concatenation.
9. Reshape data using hierarchical indexing, stacking, and unstacking.

## **Required Libraries**

We will use the following Python libraries:

- `pandas` for data manipulation and wrangling.
- `numpy` for numerical operations and random data generation.
- `re` for regular expressions and text pattern matching.

# **Reference Notes:**
This notebook is based on the topic **Data Wrangling: Clean, Transform, Merge, and Reshape**.

For additional reading, please refer to: **Wes McKinney, Python for Data Analysis**, Chapters 7 and 8.

#### **Mount to Google Drive**

In [3]:
# Mount to Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

### **Import Required Libraries**

Most data wrangling tasks in this notebook use `pandas` and `NumPy`. Therefore, we begin by importing these libraries.

In [1]:
# Load library
import pandas as pd
import numpy as np

## **1: Missing data: detect, fill, forward-fill, impute**

In [2]:
# Create a mock data
# Set a seed for reproducibility
np.random.seed(1312)
df = pd.DataFrame(np.random.standard_normal((7,3)))
df

          0         1         2
0  0.849933 -0.142354  1.658247
1  0.096458 -0.463639 -0.621719
2 -0.157222  0.106894 -0.970226
3  0.411543 -0.493338 -0.374906
4  0.144656  1.082482  0.975774
5 -0.759141  0.701347 -0.538854
6 -0.496170 -0.490029 -1.265389

### **iloc -> integer-location based indexing**

In [4]:
# Randomly add in the missing data
df.iloc[:4, 1] = np.nan
df.iloc[:2, 2] = np.nan
df

          0         1         2
0  0.849933       NaN       NaN
1  0.096458       NaN       NaN
2 -0.157222       NaN -0.970226
3  0.411543       NaN -0.374906
4  0.144656  1.082482  0.975774
5 -0.759141  0.701347 -0.538854
6 -0.496170 -0.490029 -1.265389

In [5]:
# Filling the NaN with a constant
# Sentinel data -> placeholders
df.fillna(-999)

          0           1           2
0  0.849933 -999.000000 -999.000000
1  0.096458 -999.000000 -999.000000
2 -0.157222 -999.000000   -0.970226
3  0.411543 -999.000000   -0.374906
4  0.144656    1.082482    0.975774
5 -0.759141    0.701347   -0.538854
6 -0.496170   -0.490029   -1.265389

In [ ]:
# Fill missing values differently for each column
filled_df = df.fillna({1: 0.67, 2: -1.11})

print("Filled DataFrame:")
display(filled_df)

print("Original DataFrame remains unchanged:")
display(df)

Filled DataFrame:

          0         1         2
0  0.849933  0.670000 -1.110000
1  0.096458  0.670000 -1.110000
2 -0.157222  0.670000 -0.970226
3  0.411543  0.670000 -0.374906
4  0.144656  1.082482  0.975774
5 -0.759141  0.701347 -0.538854
6 -0.496170 -0.490029 -1.265389

Original DataFrame remains unchanged:

          0         1         2
0  0.849933       NaN       NaN
1  0.096458       NaN       NaN
2 -0.157222       NaN -0.970226
3  0.411543       NaN -0.374906
4  0.144656  1.082482  0.975774
5 -0.759141  0.701347 -0.538854
6 -0.496170 -0.490029 -1.265389

In [6]:
# Change cell at (2,0) to 0.37
# This will change the data frame permanently
df.iloc[2,0] = 0.37
df

          0         1         2
0  0.849933       NaN       NaN
1  0.096458       NaN       NaN
2  0.370000       NaN -0.970226
3  0.411543       NaN -0.374906
4  0.144656  1.082482  0.975774
5 -0.759141  0.701347 -0.538854
6 -0.496170 -0.490029 -1.265389

In [7]:
# Another dummy data 2
np.random.seed(1234)
df = pd.DataFrame(np.random.standard_normal((6,3)))
df

          0         1         2
0  0.471435 -1.190976  1.432707
1 -0.312652 -0.720589  0.887163
2  0.859588 -0.636524  0.015696
3 -2.242685  1.150036  0.991946
4  0.953324 -2.021255 -0.334077
5  0.002118  0.405453  0.289092

In [8]:
# iloc - integer index
df.iloc[2:, 1] = np.nan
df.iloc[4:, 2] = np.nan
df

          0         1         2
0  0.471435 -1.190976  1.432707
1 -0.312652 -0.720589  0.887163
2  0.859588       NaN  0.015696
3 -2.242685       NaN  0.991946
4  0.953324       NaN       NaN
5  0.002118       NaN       NaN

In [9]:
# 'ffill' -> forward fill
# uses the previous valid (non-missing) value to replace the NaN
df.ffill()

          0         1         2
0  0.471435 -1.190976  1.432707
1 -0.312652 -0.720589  0.887163
2  0.859588 -0.720589  0.015696
3 -2.242685 -0.720589  0.991946
4  0.953324 -0.720589  0.991946
5  0.002118 -0.720589  0.991946

In [10]:
# fill na limit to 2
df.ffill(limit=2)

          0         1         2
0  0.471435 -1.190976  1.432707
1 -0.312652 -0.720589  0.887163
2  0.859588 -0.720589  0.015696
3 -2.242685 -0.720589  0.991946
4  0.953324       NaN  0.991946
5  0.002118       NaN  0.991946

In [11]:
# Another example 3
data = pd.Series([1., np.nan, 3.5, np.nan, 7])
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [12]:
# Data imputation using median
data.fillna(data.median())

0    1.0
1    3.5
2    3.5
3    3.5
4    7.0
dtype: float64

### **Key takeaway:**  
`fillna()` returns a new object by default.
- The original DataFrame changes only if we assign the result back to the same variable or use `inplace=True`.

## **2. Duplicate data: detect and remove**

In [13]:
# Example data with duplicate rows
data = pd.DataFrame({"k1": ['one', 'two'] * 3 + ["two"],
                     "k2": [1, 1, 2, 3, 3, 4, 4,]})
data

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

### The ***duplicated() function*** returns a ***Boolean Series*** indicating whether each row is a duplicate to those in an ***earlier row***

In [14]:
# Detect duplication of data row-wise
# data.duplicated?
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [15]:
# Returns a DataFrame with rows where the duplicated array is filtered out
data.drop_duplicates()

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [16]:
# Add dummy data by create a new column
data['v1'] = range(7) # or replace with calculation to get the values to input into a new column
data

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [17]:
# Filter duplicates based only on the "k1" column
# By default, keep the first observed value combination
data.drop_duplicates(['k1'])

    k1  k2  v1
0  one   1   0
1  two   1   1

In [19]:
# Passing keep="last" will return the last one
# Remove index 5
print(data)
print('\n--------------\n')
data.drop_duplicates(['k1', 'k2'], keep='last') # keep the last duplicated values instead of first duplicated values

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

--------------

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

## **3. Value transformation: map, replace, rename**

In [20]:
# Mock data
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon',
                              'pastrami', 'corned beef', 'bacon',
                              'pastrami', 'honey ham', 'nova lox'],
                     'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

          food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     pastrami     6.0
4  corned beef     7.5
5        bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [21]:
# Mapping of each distinct animal type
# This is a library of food to animal
meat_to_animal = {
    "bacon": "pig",
    "pulled pork": "pig",
    "pastrami": "cow",
    "corned beef": "cow",
    "honey ham": "pig",
    "nova lox": "salmon"
}
meat_to_animal

{'bacon': 'pig',
 'pulled pork': 'pig',
 'pastrami': 'cow',
 'corned beef': 'cow',
 'honey ham': 'pig',
 'nova lox': 'salmon'}

In [22]:
# Mapping method
data['animal'] = data['food'].map(meat_to_animal)
data

          food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

### **Replacing Values**

In [23]:
# Mock data
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [24]:
# Set -999 values as sentinel value for missing data
# sentinel value -> unique value indicating certain meaning
# Special value that is used to signal the end of a sequence, indicate an error,
# or serve as a termination condition in a program.
data.replace(-999, 'No data available')

0                  1.0
1    No data available
2                  2.0
3    No data available
4              -1000.0
5                  3.0
dtype: object

In [25]:
# Replace multiple sentinel values at once
# By using a list
data.replace([-999, -1000], 'No data available')

0                  1.0
1    No data available
2                  2.0
3    No data available
4    No data available
5                  3.0
dtype: object

In [26]:
# Use a different replacement for each sentinel value
data.replace([-999, -1000], ['No data available', 'Tiada maklumat'])

0                  1.0
1    No data available
2                  2.0
3    No data available
4       Tiada maklumat
5                  3.0
dtype: object

In [27]:
# Argument passed as a dictionary
data.replace({-999: 'No data available', -1000: 'no no no'})

0                  1.0
1    No data available
2                  2.0
3    No data available
4             no no no
5                  3.0
dtype: object

### **Renaming Axis Indexes**

In [28]:
# Create example DataFrame
data = pd.DataFrame(
    np.arange(12).reshape((3, 4)),
    index = ['ohio', 'ukm', 'bangi'],
    columns = ['one', 'two', 'tiga', 'empat']
)

data

       one  two  tiga  empat
ohio     0    1     2      3
ukm      4    5     6      7
bangi    8    9    10     11

In [30]:
# Add another column
data['five'] = np.random.standard_normal(3)
data

       one  two  tiga  empat      five
ohio     0    1     2      3 -0.655969
ukm      4    5     6      7  0.193421
bangi    8    9    10     11  0.553439

In [31]:
# Define a transform() function
# Rename indexes
# To uppercase
def transform(x):
    return x[:].upper()

data.index.map(transform)

Index(['OHIO', 'UKM', 'BANGI'], dtype='object')

In [32]:
# Rename indexes
# To uppercase
data.index = data.index.map(transform)
data

       one  two  tiga  empat      five
OHIO     0    1     2      3 -0.655969
UKM      4    5     6      7  0.193421
BANGI    8    9    10     11  0.553439

### Create a transformed version of a dataset ***without modifying the original***, a useful method is ***`rename()`***

In [33]:
# Rename without changing the original DataFrame
renamed_data = data.rename(index=str.title, columns=str.upper)
renamed_data

       ONE  TWO  TIGA  EMPAT      FIVE
Ohio     0    1     2      3 -0.655969
Ukm      4    5     6      7  0.193421
Bangi    8    9    10     11  0.553439

In [34]:
# Rename can be used in conjunction with a dictionary-like object
data.rename(index = {'OHIO': 'New York', 'New': 'Old'},
            columns = {'tiga': 'peekaboo', 'five': 'Seven'})

          one  two  peekaboo  empat     Seven
New York    0    1         2      3 -0.655969
UKM         4    5         6      7  0.193421
BANGI       8    9        10     11  0.553439

In [35]:
# Display original data
data

       one  two  tiga  empat      five
OHIO     0    1     2      3 -0.655969
UKM      4    5     6      7  0.193421
BANGI    8    9    10     11  0.553439

## **4. Binning and outlier handling**
- used to <font color='red'>**transform continuous data**</font> into <font color='red'>**discrete categories**</font> or <font color='red'>**intervals (bins)**</font>

In [36]:
# Mock data
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

### **Understanding Interval Notation**

In pandas binning output:

- `(18, 25]` means values greater than 18 and up to 25 are included.
- `(` or `)` means the boundary is excluded.
- `[` or `]` means the boundary is included.

For example, `(18, 25]` includes 19, 20, 21, 22, 23, 24, and 25, but excludes 18.

In [37]:
# Divide into bins of 18 to 25, 26 to 35, 36 to 60, and finally 61 and older
# returns a Categorical object
bins = [18, 25, 35, 100]
age_cut = pd.cut(ages, bins)
age_cut

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (35, 100], (35, 100], (35, 100], (25, 35]]
Length: 12
Categories (3, interval[int64, right]): [(18, 25] < (25, 35] < (35, 100]]

### **Unique pandas categorical object**

In [38]:
# Codes
age_cut.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 2, 2, 2, 1], dtype=int8)

In [39]:
# Categories
age_cut.categories

IntervalIndex([(18, 25], (25, 35], (35, 100]], dtype='interval[int64, right]')

In [40]:
# Accessing single elements
# closed -> inclusive
age_cut.categories[2]

Interval(35, 100, closed='right')

In [41]:
# Count number of each category
pd.Series(age_cut).value_counts()

(18, 25]     5
(35, 100]    4
(25, 35]     3
Name: count, dtype: int64

In [42]:
# Method 2: Count the number of observations in each age group
age_cut.value_counts()

(18, 25]     5
(25, 35]     3
(35, 100]    4
Name: count, dtype: int64

In [43]:
# Inclusive of left, exclusive (not include) right
pd.cut(ages, bins, right=False)

[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [35, 100), [35, 100), [35, 100), [25, 35)]
Length: 12
Categories (3, interval[int64, left]): [[18, 25) < [25, 35) < [35, 100)]

In [44]:
# Exclusive of left, inclusive of right
pd.cut(ages, bins, right=True)

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (35, 100], (35, 100], (35, 100], (25, 35]]
Length: 12
Categories (3, interval[int64, right]): [(18, 25] < (25, 35] < (35, 100]]

In [45]:
# Override the default interval-based bin labeling by passing a list or
# array to the labels option
gp_names = ["Youth", "MiddleAge", "Senior"]
pd.cut(ages, bins, labels=gp_names)

['Youth', 'Youth', 'Youth', 'MiddleAge', 'Youth', ..., 'MiddleAge', 'Senior', 'Senior', 'Senior', 'MiddleAge']
Length: 12
Categories (3, object): ['Youth' < 'MiddleAge' < 'Senior']

In [46]:
# Some mock data
data = np.random.uniform(size=20)
data

array([0.39720258, 0.78873014, 0.31683612, 0.56809865, 0.86912739,
       0.43617342, 0.80214764, 0.14376682, 0.70426097, 0.70458131,
       0.21879211, 0.92486763, 0.44214076, 0.90931596, 0.05980922,
       0.18428708, 0.04735528, 0.67488094, 0.59462478, 0.53331016])

In [48]:
# Pass an integer number of bins to pandas.cut to compute equal-length bins
# Based on the minimum and maximum values in the data
# Compute equal-length bins
# four quadrants -> each is 25% = 4 bins
# Precision=2 option limits the decimal precision to two digits
pd.cut(data, 4, precision=2)

[(0.27, 0.49], (0.71, 0.92], (0.27, 0.49], (0.49, 0.71], (0.71, 0.92], ..., (0.046, 0.27], (0.046, 0.27], (0.49, 0.71], (0.49, 0.71], (0.49, 0.71]]
Length: 20
Categories (4, interval[float64, right]): [(0.046, 0.27] < (0.27, 0.49] < (0.49, 0.71] <
                                           (0.71, 0.92]]

In [50]:
# Pandas.qcut bins the data based on sample quantiles
# Set the random seed
np.random.seed(5108)
data = np.random.standard_normal(size=1000) # 1000 data points
quartiles = pd.qcut(data, 4, precision = 2) # cut into 4 bins, with 2 decimal
quartiles

[(-0.0011, 0.66], (-3.0599999999999996, -0.68], (-3.0599999999999996, -0.68], (0.66, 3.04], (-0.68, -0.0011], ..., (-0.68, -0.0011], (-0.0011, 0.66], (-3.0599999999999996, -0.68], (-0.0011, 0.66], (-0.68, -0.0011]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.0599999999999996, -0.68] < (-0.68, -0.0011] < (-0.0011, 0.66] <
                                           (0.66, 3.04]]

In [51]:
# Count the number of observations in each quantile group
quartiles.value_counts()

(-3.0599999999999996, -0.68]    250
(-0.68, -0.0011]                250
(-0.0011, 0.66]                 250
(0.66, 3.04]                    250
Name: count, dtype: int64

In [53]:
# Display data content, TOP 5 data
data[:5]

array([ 0.07622227, -0.77913555, -1.7399978 ,  1.17071758, -0.60761222])

In [54]:
# Another example
# Based on user-defined quartiles
pd.cut(data, [0, 0.1, 0.5, 0.9,1.]).value_counts()

(0.0, 0.1]     37
(0.1, 0.5]    164
(0.5, 0.9]    110
(0.9, 1.0]     31
Name: count, dtype: int64

### **Detecting and Filtering Outliers**

In [55]:
# DataFrame with some normally distributed data
# DataFrame of 1000x4
np.random.seed(123)

# create standard normal distribution values
data = pd.DataFrame(np.random.randn(1000, 4))
data

            0         1         2         3
0   -1.085631  0.997345  0.282978 -1.506295
1   -0.578600  1.651437 -2.426679 -0.428913
2    1.265936 -0.866740 -0.678886 -0.094709
3    1.491390 -0.638902 -0.443982 -0.434351
4    2.205930  2.186786  1.004054  0.386186
..        ...       ...       ...       ...
995 -0.499897  0.587647 -0.926542  1.736982
996 -0.459550  0.125822 -1.119947 -0.521887
997 -2.013430 -0.028708 -0.103142 -1.761313
998 -0.185167  0.504077  1.354567 -0.907952
999 -1.818045 -0.122733  1.794486 -0.320510

[1000 rows x 4 columns]

In [56]:
# Generate descriptive statistics for each column
data.describe()

                 0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.007502     0.039160    -0.010286     0.024285
std       0.977024     0.973484     1.012230     0.970421
min      -3.167055    -2.920029    -3.801378    -3.231055
25%      -0.662012    -0.636160    -0.687717    -0.599195
50%      -0.024843     0.062549     0.007035     0.038718
75%       0.613950     0.672448     0.664586     0.683228
max       3.050755     2.850708     2.766603     3.571579

In [58]:
# Extract column 2 from the DataFrame
col = data[2]

# Display values in column 2 where the absolute value is greater than 3
col[col.abs() > 3]

409   -3.801378
423   -3.587494
510   -3.066988
Name: 2, dtype: float64

In [61]:
# Check whether each value is greater than 3 or less than -3
condition = np.abs(data) > 3

# Select rows where at least one column satisfies the condition
data[condition.any(axis=1)]

            0         1         2         3
48   0.199582 -0.126118  0.197019 -3.231055
182  0.272735  0.425336 -0.230904  3.571579
235 -3.167055 -0.713989 -1.112364 -1.254184
409  0.151037  0.069403 -3.801378 -1.127172
423  0.231228  1.076113 -3.587494  1.148869
510  0.506533  0.644099 -3.066988 -1.349275
910  3.050755  0.296552 -0.481843  0.930787

In [63]:
# Identify values greater than 3 or less than -3
condition = np.abs(data) > 3

# Replace values above 3 with 3, and values below -3 with -3
data[condition] = np.sign(data) * 3

# Check the summary statistics after capping the outliers
data.describe()

                 0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.007386     0.039160    -0.008831     0.023944
std       0.976340     0.973484     1.007422     0.967746
min      -3.000000    -2.920029    -3.000000    -3.000000
25%      -0.662012    -0.636160    -0.687717    -0.599195
50%      -0.024843     0.062549     0.007035     0.038718
75%       0.613950     0.672448     0.664586     0.683228
max       3.000000     2.850708     2.766603     3.000000

## **5. Permutation and Random Sampling**
- Permutation - process of rearranging the order of elements within a dataset
- This rearrangement is often **done randomly**, meaning that the elements are shuffled into a **new, unpredictable order**.

In [64]:
# Create a 2D array with 5 rows and 7 columns
df = pd.DataFrame(np.arange(35).reshape(5, 7))
df

    0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

In [65]:
# Randomly rearrange the row order
np.random.seed(123)

sampler = np.random.permutation(5)
sampler

array([1, 3, 4, 0, 2])

In [66]:
# Reorder the rows based on the random row index order
df.iloc[sampler]

    0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34
0   0   1   2   3   4   5   6
2  14  15  16  17  18  19  20

In [67]:
# Randomly reorder all rows using sample() with a fixed random state
df.sample(frac=1, random_state=123)

    0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34
0   0   1   2   3   4   5   6
2  14  15  16  17  18  19  20

### **Notes:**
- **`frac=1`** means sample 100% of the rows
- Since all rows are selected but in random order, the DataFrame is shuffled.

In [69]:
# Generate a random order for the 7 column indexes
column_sampler = np.random.permutation(7)
column_sampler

array([3, 5, 4, 2, 6, 0, 1])

In [71]:
# Randomly reorder the columns of the DataFrame
print(df)
print('\n--------\n')

# Generate a random order for the 7 column indexes
column_sampler = np.random.permutation(7) # changed every time runned the codes

# Reorder the columns based on the random column order
df.iloc[:, column_sampler]

    0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

--------

    3   2   1   6   5   0   4
0   3   2   1   6   5   0   4
1  10   9   8  13  12   7  11
2  17  16  15  20  19  14  18
3  24  23  22  27  26  21  25
4  31  30  29  34  33  28  32

In [73]:
# Select a random subset of 4 rows without replacement
df.sample(n=4, replace=False, random_state=123)

    0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34
0   0   1   2   3   4   5   6

In [74]:
# Example dataset
obj = pd.Series([5, 7, -1, 6, 4])
obj

0    5
1    7
2   -1
3    6
4    4
dtype: int64

### <font color='red'>**`replace=False`**</font>
- indicates that we are performing sampling without replacement

In [75]:
# Generate a sample with replacement
obj.sample(n=5, replace=True, random_state=123)

2   -1
4    4
2   -1
1    7
3    6
dtype: int64

## **6. String cleaning and regular expressions**
String data often contains inconsistent spacing, punctuation, and formatting.
- Before text can be analysed, we usually need to split, trim, search, and extract patterns.
- Simple string methods are useful for basic cleaning, while regular expressions are useful when the pattern is more complex.

### **String Manipulation**

In [76]:
# A comma-separated string can be broken into pieces with split
val = "a,b,  abu  bakar"
val.split(",")

['a', 'b', '  abu  bakar']

In [80]:
# Split is often combined with strip to trim whitespace
pieces = [x.strip() for x in val.split(",")]
pieces

['a', 'b', 'abu  bakar']

In [81]:
# Substrings could be concatenated together with addition
first, second, third = pieces
first + "&" + second + "&" + third

'a&b&abu  bakar'

In [82]:
# Another way
"@".join(pieces)

'a@b@abu  bakar'

In [83]:
# Return starting index of the first occurrence of passed substring
# If found in the string
val.index("u")

8

In [84]:
# Count returns the number of occurrences
val.count(",")

2

### **Regular Expressions**
***regex*** describes a ***pattern to locate*** in the text, which can then be used for many purposes

### <font color='red'>**`r"\s+"`**</font>
- <font color='red'>**`r""`**</font>: This designates a **raw string literal**, which is often used for regular expressions to avoid escaping issues with **backslashes (`\`)**.
- <font color='red'>**`\s+`**</font>: This is the actual regular expression pattern. It **matches one or more whitespace characters**.

In [85]:
# Regex describing one or more whitespace characters -> \s+
# raw string (r"\s+") is often preferred in regular expressions to enhance readability and avoid potential issues with escaping
import re
text = "foo bar\t baz \tqux"
print(text)
print('\n----\n')
re.split(r"\s+", text)

foo bar	 baz 	qux

----

['foo', 'bar', 'baz', 'qux']

In [86]:
# Compile the regex with re.compile, forming a reusable regex object
# r'\s+' refers to sequence of whitespace
# Avoid unwanted escaping with \ in a regular expression
regex = re.compile(r"\s+")
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [89]:
# A block of text example
text = """
Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com
"""

# Display text
print(text)

# The pattern to search
# Match a typical email address pattern
pattern = r"[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}"

# re.IGNORECASE makes the regex case insensitive
regex = re.compile(pattern, flags=re.IGNORECASE)

Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com

In [90]:
# Extract the information based on the pattern
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

### **String Functions in pandas**
Cleaning up a messy dataset for analysis often requires a lot of string manipulation

In [91]:
# A column containing strings with missing data
# in dictionary form
data = {"Dave": "dave@google.com", "Steve": "steve@gmail.com",
        "Rob": "rob@gmail.com", "Wes": np.nan}
data = pd.Series(data)
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [92]:
# Check missing data
data.isna()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [93]:
# Series has array-oriented methods for string operations that skip over
# and propagate NA values
data.str.contains("google")

Dave      True
Steve    False
Rob      False
Wes        NaN
dtype: object

In [94]:
# String data type
data_as_string = data.astype('string')
data_as_string

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                 <NA>
dtype: string

In [95]:
# Boolean data type
data_as_string.str.contains('gmail')

Dave     False
Steve     True
Rob       True
Wes       <NA>
dtype: boolean

## **7. Categorical data and dummy variables**
- Categorical data refers to variables that represent groups or labels rather than continuous numerical values.
    - Examples include gender, treatment group, product category, education level, and movie genre.

- In pandas, categorical data can be stored using the `category` data type. This can make the data more memory-efficient and can also help preserve the logical order of categories.

- After understanding categorical data, we will learn how to convert categories into dummy variables, also known as one-hot encoding. This is commonly required before using categorical variables in machine learning models.

### **Categorical Data**
Categorical variables are common in real datasets, such as gender, treatment group, product category, or movie genre.
- Machine learning models usually require numerical input, so categorical variables often need to be encoded.
- One common method is dummy-variable encoding, also known as one-hot encoding.

In [96]:
# A mock data
values = pd.Series(['apple', 'orange', 'apple',
                    'apple'] * 2)
values

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
dtype: object

In [97]:
# Extract distinct values
pd.unique(values)

array(['apple', 'orange'], dtype=object)

In [98]:
# Count
pd.Series(values).value_counts()

apple     6
orange    2
Name: count, dtype: int64

### **Categorical Extension Type in pandas**
integer-based categorical representation or ***encoding***

In [99]:
# Some example Series
fruits = ['apple', 'orange', 'apple', 'apple'] * 2
N = len(fruits)
rng = np.random.default_rng(seed=12345)

df = pd.DataFrame({'fruit': fruits,
                   'basket_id': np.arange(N),
                   'count': rng.integers(3, 15, size=N),
                   'weight': rng.uniform(0, 4, size=N)},
                  columns=['basket_id', 'fruit', 'count', 'weight'])
df

   basket_id   fruit  count    weight
0          0   apple     11  1.564438
1          1  orange      5  1.331256
2          2   apple     12  2.393235
3          3   apple      6  0.746937
4          4   apple      5  2.691024
5          5  orange     12  3.767211
6          6   apple     10  0.992983
7          7   apple     11  3.795525

In [100]:
# Convert df['fruit'] into categorical; original is a string
fruit_cat = df['fruit'].astype('category')
fruit_cat

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [108]:
# Accessing the array attribute
c = fruit_cat.array
type(c)

pandas.core.arrays.categorical.Categorical

In [109]:
# Categories
c.categories

Index(['apple', 'orange'], dtype='object')

In [105]:
# codes
c.codes

array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

#### <font color='red'>**`enumerate()`**</font>
- is used to **create a dictionary** that **maps the index positions of the categories** to their **corresponding values**

In [106]:
# Mapping between codes and categories
# Returns pairs of index and value.
dict(enumerate(c.categories))

{0: 'apple', 1: 'orange'}

### **Computations with Categoricals**

In [116]:
# Some mock data
rng = np.random.default_rng(seed=12345)
draws = rng.standard_normal(1000)
draws[:5]

array([-1.42382504,  1.26372846, -0.87066174, -0.25917323, -0.07534331])

In [117]:
# Compute a quartile binning
bins = pd.qcut(draws, 4) # cut into 4bins
bins

[(-3.121, -0.675], (0.687, 3.211], (-3.121, -0.675], (-0.675, 0.0134], (-0.675, 0.0134], ..., (0.0134, 0.687], (0.0134, 0.687], (-0.675, 0.0134], (0.0134, 0.687], (-0.675, 0.0134]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.121, -0.675] < (-0.675, 0.0134] < (0.0134, 0.687] <
                                           (0.687, 3.211]]

In [118]:
# Using labels argument
bins = pd.qcut(draws, 4, labels=['Q1', 'Q2', 'Q3', 'Q4'])
bins

['Q1', 'Q4', 'Q1', 'Q2', 'Q2', ..., 'Q3', 'Q3', 'Q2', 'Q3', 'Q2']
Length: 1000
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [119]:
# Accessing codes
bins.codes[:10] # 0, 1, 2, 3 = 4

array([0, 3, 0, 1, 1, 0, 0, 2, 2, 0], dtype=int8)

In [123]:
# Use groupby to extract summary statistics
bins = pd.Series(bins, name='quartile')
results = (pd.Series(draws) # create a Series by using (draws) data
           .groupby(bins, observed=True) # group by bins = Q1, Q2, Q3, Q4
           .agg(['count', 'min', 'max']) # Aggregare to count, min, and max
           .reset_index())
results

  quartile  count       min       max
0       Q1    250 -3.119609 -0.678494
1       Q2    250 -0.673305  0.008009
2       Q3    250  0.018753  0.686183
3       Q4    250  0.688282  3.211418

### **Categorical Methods**

In [129]:
# Some mock data
s = pd.Series(['a', 'b', 'c', 'd'] * 2) # in Python will auto save the data as object datatype
cat_s = s.astype('category') # thats why need to change the datatype to category
cat_s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [133]:
# cat provides access to categorical methods -> the codes
# returns the integer codes associated with each category in the categorical series
cat_s.cat.codes

0    0
1    1
2    2
3    3
4    0
5    1
6    2
7    3
dtype: int8

In [134]:
# Accessing the categories data
cat_s.cat.categories

Index(['a', 'b', 'c', 'd'], dtype='object')

In [135]:
# set_categories() method to change new category
actual_categories = ['a', 'b', 'c', 'd', 'e']
cat_s2 = cat_s.cat.set_categories(actual_categories)
cat_s2

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (5, object): ['a', 'b', 'c', 'd', 'e']

In [136]:
# value_counts for cat_s
cat_s.value_counts()

a    2
b    2
c    2
d    2
Name: count, dtype: int64

In [132]:
# value_counts for cat_s2
cat_s2.value_counts()

a    2
b    2
c    2
d    2
e    0
Name: count, dtype: int64

### **Hierarchical Indexing** (multiple index)

In [138]:
# An example
data = pd.Series(np.random.uniform(size=9),
                 index=[["a", "a", "a", "b", "b", "c", "c", "d", "d"],
                        [1,2,3,1,3,1,2,2,3]])
data

a  1    0.654721
   2    0.373801
   3    0.234513
b  1    0.987995
   3    0.765996
c  1    0.777004
   2    0.027982
d  2    0.173907
   3    0.154082
dtype: float64

In [139]:
# Access the index
data.index

MultiIndex([('a', 1),
            ('a', 2),
            ('a', 3),
            ('b', 1),
            ('b', 3),
            ('c', 1),
            ('c', 2),
            ('d', 2),
            ('d', 3)],
           )

In [140]:
# Partial indexing
data['b']

1    0.987995
3    0.765996
dtype: float64

In [141]:
# Partial indexing
data['b':'c']

b  1    0.987995
   3    0.765996
c  1    0.777004
   2    0.027982
dtype: float64

In [142]:
# Partial indexing
# loc[] -> label-based indexing
data.loc[['b', 'd']]

b  1    0.987995
   3    0.765996
d  2    0.173907
   3    0.154082
dtype: float64

In [143]:
# Partial indexing
print(data)
print('\n---------\n')
data.loc[:, 2]

a  1    0.654721
   2    0.373801
   3    0.234513
b  1    0.987995
   3    0.765996
c  1    0.777004
   2    0.027982
d  2    0.173907
   3    0.154082
dtype: float64

---------

a    0.373801
c    0.027982
d    0.173907
dtype: float64

In [144]:
# Rearrange this data into a DataFrame using its unstack method
data.unstack()

          1         2         3
a  0.654721  0.373801  0.234513
b  0.987995       NaN  0.765996
c  0.777004  0.027982       NaN
d       NaN  0.173907  0.154082

In [145]:
# Reverse the operation of unstack -> stack
data.unstack().stack()

a  1    0.654721
   2    0.373801
   3    0.234513
b  1    0.987995
   3    0.765996
c  1    0.777004
   2    0.027982
d  2    0.173907
   3    0.154082
dtype: float64

In [147]:
# Another example
frame = pd.DataFrame(np.arange(12).reshape((4, 3)),
                     index=[["a", "a", "b", "b"], [1, 2, 1, 2]],
                     columns=[["Ohio", "Ohio", "Colorado"],
                              ["Green", "Red", "Green"]])
frame

     Ohio     Colorado
    Green Red    Green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

In [148]:
# Add key names
frame.index.names = ["key1", "key2"]
frame.columns.names = ["state", "color"]
frame

state      Ohio     Colorado
color     Green Red    Green
key1 key2
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [151]:
# Partial indexing
frame["Ohio"]

color      Green  Red
key1 key2
a    1         0    1
     2         3    4
b    1         6    7
     2         9   10

### **Reordering and Sorting Levels**

In [152]:
# Rearrange key
frame.swaplevel("key1", "key2")

state      Ohio     Colorado
color     Green Red    Green
key2 key1
1    a        0   1        2
2    a        3   4        5
1    b        6   7        8
2    b        9  10       11

In [153]:
# Another example of rearrange
# level=1 -> the sorting is based on the values in the second level of the index.
print(frame)
print('\n-------\n')
frame.sort_index(level=1)

state      Ohio     Colorado
color     Green Red    Green
key1 key2
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

-------

state      Ohio     Colorado
color     Green Red    Green
key1 key2
a    1        0   1        2
b    1        6   7        8
a    2        3   4        5
b    2        9  10       11

### **Summary Statistics by Level**

In [154]:
# Sum
frame.groupby(level="key2").sum()

state  Ohio     Colorado
color Green Red    Green
key2
1         6   8       10
2        12  14       16

In [157]:
# Transpose
frame.T

key1            a     b
key2            1  2  1   2
state    color
Ohio     Green  0  3  6   9
         Red    1  4  7  10
Colorado Green  2  5  8  11

In [158]:
# Transpose and Group by 'color', then sum, and Transpose back to ori
frame.T.groupby(level="color").sum().T

color      Green  Red
key1 key2
a    1         2    1
     2         8    4
b    1        14    7
     2        20   10

### **Indexing with a DataFrame’s columns**

In [159]:
# Example dataframe
frame = pd.DataFrame({"a": range(7), "b": range(7, 0, -1),
                      "c": ["one", "one", "one", "two", "two",
                            "two", "two"],
                      "d":[0,1,2,0,1,2,3]})
frame

   a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3

In [160]:
# Create a new DataFrame using one or more of its columns as the index
frame2 = frame.set_index(["c", "d"])
frame2

       a  b
c   d
one 0  0  7
    1  1  6
    2  2  5
two 0  3  4
    1  4  3
    2  5  2
    3  6  1

In [162]:
# Leave the column intact
frame.set_index(["c", "d"], drop=False) # Remain c, d in the column

       a  b    c  d
c   d
one 0  0  7  one  0
    1  1  6  one  1
    2  2  5  one  2
two 0  3  4  two  0
    1  4  3  two  1
    2  5  2  two  2
    3  6  1  two  3

In [163]:
# Move the index back to columns
frame2.reset_index()

     c  d  a  b
0  one  0  0  7
1  one  1  1  6
2  one  2  2  5
3  two  0  3  4
4  two  1  4  3
5  two  2  5  2
6  two  3  6  1

## **8. Combining datasets: merge, join, concatenate**
After cleaning individual datasets, the next common task is to combine information from multiple tables.
- This is especially important when different parts of the data are stored separately, such as customer information in one table and transaction records in another table.

In pandas, the most common tools are:

- `merge()` for database-style joins using key columns.
- `concat()` for stacking or combining objects along rows or columns.
- `join()` for combining based on indexes.

### **Database-Style DataFrame Joins**

In [ ]:
# Example datasets
df1 = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "a", "b"],
                    "data1": pd.Series(range(7), dtype="Int64")})
df2 = pd.DataFrame({"key": ["a", "b", "d"],
                    "data2": pd.Series(range(3), dtype="Int64")})

In [ ]:
# Display df1 content
df1

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

In [ ]:
# Display df2 content
df2

  key  data2
0   a      0
1   b      1
2   d      2

In [ ]:
# By default - inner join
# keeps only the rows where the "key" values exist in both DataFrames
# Using the same common "feature"
pd.merge(df1, df2)

  key  data1  data2
0   b      0      1
1   b      1      1
2   a      2      0
3   a      4      0
4   a      5      0
5   b      6      1

In [ ]:
# Different column names
df3 = pd.DataFrame({"lkey": ["b", "b", "a", "c", "a", "a", "b"],
                    "data1": pd.Series(range(7), dtype="Int64")})
df4 = pd.DataFrame({"rkey": ["a", "b", "d"],
                    "data2": pd.Series(range(3), dtype="Int64")})

In [ ]:
# Display df3 content
df3

  lkey  data1
0    b      0
1    b      1
2    a      2
3    c      3
4    a      4
5    a      5
6    b      6

In [ ]:
# Display df4 content
df4

  rkey  data2
0    a      0
1    b      1
2    d      2

In [ ]:
# Merge - inner join by default - intersection
# Using specific key
pd.merge(df4, df3, left_on="rkey", right_on="lkey")

  rkey  data2 lkey  data1
0    a      0    a      2
1    a      0    a      4
2    a      0    a      5
3    b      1    b      0
4    b      1    b      1
5    b      1    b      6

In [ ]:
# Merge - outer join - union
print(df1)
print('\n----\n')
print(df2)
print('\n----\n')
pd.merge(df1, df2, how="outer")

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

----

  key  data2
0   a      0
1   b      1
2   d      2

----

  key  data1  data2
0   a      2      0
1   a      4      0
2   a      5      0
3   b      0      1
4   b      1      1
5   b      6      1
6   c      3   <NA>
7   d   <NA>      2

In [ ]:
# Merge - outer join - union
print(df3)
print('\n----\n')
print(df4)
print('\n----\n')
pd.merge(df3, df4, left_on="lkey", right_on="rkey", how="outer")

  lkey  data1
0    b      0
1    b      1
2    a      2
3    c      3
4    a      4
5    a      5
6    b      6

----

  rkey  data2
0    a      0
1    b      1
2    d      2

----

  lkey  data1 rkey  data2
0    a      2    a      0
1    a      4    a      0
2    a      5    a      0
3    b      0    b      1
4    b      1    b      1
5    b      6    b      1
6    c      3  NaN   <NA>
7  NaN   <NA>    d      2

### **Many-to-many merges**

In [ ]:
# A mock data
df1 = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "b"],
                    "data1": pd.Series(range(6), dtype="Int64")})
df2 = pd.DataFrame({"key": ["a", "b", "a", "b", "d"],
                    "data2": pd.Series(range(5), dtype="Int64")})

In [ ]:
# Display df1
df1

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [ ]:
# Display df2
df2

  key  data2
0   a      0
1   b      1
2   a      2
3   b      3
4   d      4

In [ ]:
# left-join
pd.merge(df1, df2, on="key", how="left")

   key  data1  data2
0    b      0      1
1    b      0      3
2    b      1      1
3    b      1      3
4    a      2      0
5    a      2      2
6    c      3   <NA>
7    a      4      0
8    a      4      2
9    b      5      1
10   b      5      3

In [ ]:
# inner join
# Intersection
pd.merge(df1, df2, how="inner")

  key  data1  data2
0   b      0      1
1   b      0      3
2   b      1      1
3   b      1      3
4   a      2      0
5   a      2      2
6   a      4      0
7   a      4      2
8   b      5      1
9   b      5      3

In [ ]:
# merge with multiple keys
left = pd.DataFrame({"key1": ["foo", "foo", "bar"],
                     "key2": ["one", "two", "one"],
                     "lval": pd.Series([1, 2, 3], dtype='Int64')})
right = pd.DataFrame({"key1": ["foo", "foo", "bar", "bar"],
                      "key2": ["one", "one", "one", "two"],
                      "rval": pd.Series([4, 5, 6, 7], dtype='Int64')})

In [ ]:
# Display left content
left

  key1 key2  lval
0  foo  one     1
1  foo  two     2
2  bar  one     3

In [ ]:
# Display right content
right

  key1 key2  rval
0  foo  one     4
1  foo  one     5
2  bar  one     6
3  bar  two     7

In [ ]:
# Outer join
pd.merge(left, right, on=["key1", "key2"], how="outer")

  key1 key2  lval  rval
0  bar  one     3     6
1  bar  two  <NA>     7
2  foo  one     1     4
3  foo  one     1     5
4  foo  two     2  <NA>

### **Concatenating Along an Axis**
***axis=0***; ***moves down*** the column

***axis=1***; ***moves across*** the column to the right

In [ ]:
# An example
arr = np.arange(12).reshape((3, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# Along the column
np.concatenate([arr, arr], axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

## **9. Reshaping data: stack, unstack, pivot**
1. Before learning `stack()` and `unstack()`, it is useful to understand hierarchical indexing. Hierarchical indexing allows a Series or DataFrame to have more than one index level. This is useful when working with grouped, multi-dimensional, or panel-like data.

2. Once the data has multiple index levels, we can reshape it using methods such as `stack()` and `unstack()`.

### **Reshaping**
reshape or pivoting - rearranging tabular data

### **Pivoting**
- a specific type of **data reshaping** operation where we:

    - **Transform data from a "long" format to a "wide" format (or vice-versa)**.
    - **Use one or more columns as new column headers**.
    - **Aggregate values in other columns to populate the new structure.**

### ***Reshaping with Hierarchical Indexing***

In [ ]:
# Example data
data = pd.DataFrame(np.arange(6).reshape((2, 3)),
                    index=pd.Index(["Ohio", "Colorado"], name="state"),
                    columns=pd.Index(["one", "two", "three"],
                                     name="number"))
data

number    one  two  three
state
Ohio        0    1      2
Colorado    3    4      5

In [ ]:
# Using the stack method to pivot the columns into the rows
result = data.stack()
result

state     number
Ohio      one       0
          two       1
          three     2
Colorado  one       3
          two       4
          three     5
dtype: int64

In [ ]:
# Rearrange
result.unstack()

number    one  two  three
state
Ohio        0    1      2
Colorado    3    4      5

In [ ]:
# Unstack a different level by passing a level number or name
result.unstack(level=0)

state   Ohio  Colorado
number
one        0         3
two        1         4
three      2         5

In [ ]:
# Using name
result.unstack(level="state")

state   Ohio  Colorado
number
one        0         3
two        1         4
three      2         5

### **`Int64`**
- Pandas data type that can handle **nullable integers**.
- **Nullable** means it can **store regular integer values** as well as **missing values** (represented as pd.NA).

In [ ]:
# Example
s1 = pd.Series([0, 1, 2, 3], index=["a", "b", "c", "d"], dtype="Int64")
s1

a    0
b    1
c    2
d    3
dtype: Int64

In [ ]:
# example 2
s2 = pd.Series([4, 5, 6], index=["c", "d", "e"], dtype="Int64")
s2

c    4
d    5
e    6
dtype: Int64

In [ ]:
# Concatenate
data2 = pd.concat([s1, s2], keys=["one", "two"])
data2

one  a    0
     b    1
     c    2
     d    3
two  c    4
     d    5
     e    6
dtype: Int64

In [ ]:
# Unstacking
data2.unstack()

        a     b  c  d     e
one     0     1  2  3  <NA>
two  <NA>  <NA>  4  5     6

In [ ]:
# Return original state
data2.unstack().stack()

one  a    0
     b    1
     c    2
     d    3
two  c    4
     d    5
     e    6
dtype: Int64

### **Computing Indicator/Dummy Variables**
Converting a categorical variable into a dummy or indicator matrix

In [ ]:
# Example dataframe
df = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "b"],
                   "data1": range(6)})
df

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [ ]:
# Get dummy dataFrame based on the key
pd.get_dummies(df["key"])

       a      b      c
0  False   True  False
1  False   True  False
2   True  False  False
3  False  False   True
4   True  False  False
5  False   True  False

In [ ]:
# Add a prefix
dummies= pd.get_dummies(df["key"], prefix="key")
dummies

   key_a  key_b  key_c
0  False   True  False
1  False   True  False
2   True  False  False
3  False  False   True
4   True  False  False
5  False   True  False

In [ ]:
# Example data from previous
df

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [ ]:
# Merging of dataset based on the same index number
print(df)
print('\n--------\n')
print(dummies)
print('\n--------\n')
df_with_dummy= df[["data1"]].join(dummies)
df_with_dummy

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

--------

   key_a  key_b  key_c
0  False   True  False
1  False   True  False
2   True  False  False
3  False  False   True
4   True  False  False
5  False   True  False

--------

   data1  key_a  key_b  key_c
0      0  False   True  False
1      1  False   True  False
2      2   True  False  False
3      3  False  False   True
4      4   True  False  False
5      5  False   True  False

#### **Notes:**
The following small dataset is used first so that the notebook can run without internet access.  
After understanding the concept, we will try the larger online movie dataset.

In [ ]:
# Small example of movie genres without using an online dataset

movies_small = pd.DataFrame({
    "movie_id": [1, 2, 3, 4, 5, 6],
    "title": ["Movie A", "Movie B", "Movie C", "Movie D", "Movie E", "Movie F"],
    "genres": [
        "Action|Comedy",
        "Drama",
        "Action|Drama",
        "Comedy",
        "Drama|Romance",
        "Action"
    ]
})

movies_small

   movie_id    title         genres
0         1  Movie A  Action|Comedy
1         2  Movie B          Drama
2         3  Movie C   Action|Drama
3         4  Movie D         Comedy
4         5  Movie E  Drama|Romance
5         6  Movie F         Action

In [ ]:
# Convert multiple genre labels into dummy variables

genre_dummies = movies_small["genres"].str.get_dummies("|")

genre_dummies

   Action  Comedy  Drama  Romance
0       1       1      0        0
1       0       0      1        0
2       1       0      1        0
3       0       1      0        0
4       0       0      1        1
5       1       0      0        0

#### **Explanation**:
In this context, `.str` is the pandas string accessor.
- It allows us to apply string-related methods to every value in a Series.
- Here, `.str.get_dummies("|")` splits the genre values using `|` and converts each genre into separate dummy-variable columns.
- 1 = Yes, this category is present
- 0 = No, this category is not present

#### **Note:**
The following example requires an internet connection because the dataset is loaded directly from an online source. If the dataset cannot be loaded, the next example will not run.

In [ ]:
# DataFrame with multiple categories
# movies.dat -> Data can be downlaoded here: https://bit.ly/3VA5elU
mnames = ["movie_id", "title", "genres"]
movies = pd.read_table("https://bit.ly/3VA5elU", sep="::", header=None,
                       names=mnames, engine="python")
movies[:6]

   movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller

In [ ]:
# Get data from the genres column
dummies = movies["genres"].str.get_dummies("|")
dummies.iloc[:6, :6]

   Action  Adventure  Animation  Children's  Comedy  Crime
0       0          0          1           1       1      0
1       0          1          0           1       0      0
2       0          0          0           0       1      0
3       0          0          0           0       1      0
4       0          0          0           0       1      0
5       1          0          0           0       0      1

# **Summary**

In this notebook, we covered the main steps in data wrangling:

1. Handling missing values.
2. Removing duplicate records.
3. Transforming, replacing, and renaming values.
4. Binning continuous variables into categories.
5. Detecting and capping outliers.
6. Sampling and shuffling data.
7. Cleaning text and extracting patterns using regular expressions.
8. Working with categorical variables.
9. Combining datasets using merge and concatenation.
10. Reshaping data using stack and unstack.

These skills are important because most real-world data is not immediately ready for analysis. Data wrangling helps us prepare the data so that statistical analysis, visualization, and machine learning can be performed correctly.

# **All the best and good luck!!!**